POST http://localhost:3001/api/patients
content-type: application/json

{
  "name": "Sandesh Hyoju",
  "dateOfBirth": "1988-02-15",
  "ssn": "150288-2557",
  "gender": "male",
  "occupation": "FULLSTACK developer"
}


###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
content-type: application/json

{
  "date":"2021-12-12",
  "type": "OccupationalHealthcare",
  "specialist": "Sandesh Hyoju",
  "description": "Meet with the doctor",
  "employerName": "smarty",
  "sickLeave": {
    "startDate": "2021-12-13",
    "endDate": "2021-12-14"
  }
}