GET http://localhost:3003

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Sandesh First post",
  "author": "Sandesh Hyoju",
  "url": "http://sandesh.hyoju.com",
  "likes": 10
}


###
PUT http://localhost:3003/api/blogs/61ae69019774b29ca9bc27a8
Content-Type: application/json

  {
    "likes": 5
  }


###
DELETE http://localhost:3003/api/blogs/61ae69019774b29ca9bc27a8